#pragma once

typedef enum even_e {
    EVENT_MESSAGE_RECIEVED_FINAL,
    EVENT_MESSAGE_RECIEVED_TO_TRANSFER,
    EVENT_HELP_MESSAGE_RECIEVED,
    EVENT_UPDATE_RECIEVED,
    EVENT_PAIR_REQUEST
} event;